### ISSUE TITLE
Rebuild docker image to prevent CVE on root password

### ISSUE THREAD

**Issue by thomasboussekey** [taivokasper/docker-omnidb#21]
Hello @taivokasper 

I discovered that alpine has a CVE problem described here:

https://www.zdnet.com/article/alpine-linux-docker-images-ship-a-root-account-with-no-password/

It seems that latest version of alpine are now protected against this threat.
I see on docker hub that the image was rebuild 18 days ago, but I cannot find if the alpine version was already OK at that date!

Do you think an image rebuilt is needed?

Thomas

**Comment by taivokasper** [comment]
Hi @thomasboussekey,

I have no idea. I will just rebuild the latest image.
